/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AbhaLinkRouteImport } from './routes/abha-link'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsUploadRouteImport } from './routes/records/upload'
import { Route as AppointmentsBookRouteImport } from './routes/appointments/book'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AbhaLinkRoute = AbhaLinkRouteImport.update({
  id: '/abha-link',
  path: '/abha-link',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsUploadRoute = RecordsUploadRouteImport.update({
  id: '/records/upload',
  path: '/records/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsBookRoute = AppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abha-link': typeof AbhaLinkRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/records/upload': typeof RecordsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abha-link': typeof AbhaLinkRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/records/upload': typeof RecordsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abha-link': typeof AbhaLinkRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/records/upload': typeof RecordsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abha-link'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/appointments/book'
    | '/records/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abha-link'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/appointments/book'
    | '/records/upload'
  id:
    | '__root__'
    | '/'
    | '/abha-link'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/appointments/book'
    | '/records/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbhaLinkRoute: typeof AbhaLinkRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  RecordsUploadRoute: typeof RecordsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abha-link': {
      id: '/abha-link'
      path: '/abha-link'
      fullPath: '/abha-link'
      preLoaderRoute: typeof AbhaLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/upload': {
      id: '/records/upload'
      path: '/records/upload'
      fullPath: '/records/upload'
      preLoaderRoute: typeof RecordsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/book': {
      id: '/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbhaLinkRoute: AbhaLinkRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AppointmentsBookRoute: AppointmentsBookRoute,
  RecordsUploadRoute: RecordsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
